[package]
name = "hammerload"
version = "0.4.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.3"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
hdrhistogram = "7.5.4"
